trigger: none

resources:
  repositories:
    - repository: pipelines
      name: $(project_name)/pipelines
      type: git
      ref: main

variables:
- group: devops

jobs:

############################################################################################################################################
############################################################# Application Build ############################################################
############################################################################################################################################

- template: build-templates-hml/build-pipeline-hml.yml@pipelines