trigger: none

resources:
  repositories:
    - repository: devops
      name: $(project_name)/devops
      type: git
      ref: main
    - repository: pipelines
      name: $(project_name)/pipelines
      type: git
      ref: main

variables:
- group: devops

jobs:

############################################################################################################################################
######################################################### DevOps CLI - Docker Pull #########################################################
############################################################################################################################################

- template: automation-templates/DockerPull.yml@devops

############################################################################################################################################
########################################################## DevOps CLI - Pre-Build ##########################################################
############################################################################################################################################

- template: automation-templates/PreBuild.yml@devops

############################################################################################################################################
############################################################ Branches Validation ###########################################################
############################################################################################################################################

- template: validation-templates/ValidateBranches.yml@devops
# - template: validation-templates/ValidateWorkItems.yml@devops
- template: validation-templates/PostValidation.yml@devops
- template: validation-templates/RelAbandonPullRequest.yml@devops

############################################################################################################################################
############################################################# Application Build ############################################################
############################################################################################################################################
# Habilitar apenas se existir "PR-Validation" na aplicação (ex: CRM)

#- template: build-templates-prd/build-pipeline-prd.yml@pipelines

############################################################################################################################################
#################################################### DevOps CLI - Post-Build (Failure) #####################################################
############################################################################################################################################
# Habilitar apenas se existir "PR-Validation" na aplicação (ex: CRM)

#- template: automation-templates/PostBuild.yml@devops