version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    # network_mode: "host"
    restart: always
    environment:
      MYSQL_DATABASE: 'ibm_vtal_db'   
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'      
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    # network_mode: "host"
    privileged: true
    user: root
    restart: always
    environment:
      JENKINS_SLAVE_AGENT_PORT: 9001
      JAVA_OPTS: -Duser.timezone=Brazil/East
      JAVA_TOOLS_OPTIONS: -Dfile.encoding=UTF8
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - ./.jenkins-data:/var/jenkins_home
